### ISSUE TITLE
Max supported file size?

### ISSUE THREAD

**Issue by jflasher** [openaq/openaq-quality-checks#20]
@abarciauskas-bgse do you have an idea of that maximum file size accepted as an input? I was trying with this file http://aws-athena-query-results-470049585876-us-east-1.s3.amazonaws.com/Unsaved/2018/02/23/714fa90f-1c6d-42a5-9469-22bc24a5e3a9.csv which is 5.6MB, so not that big on the scale of what we'd be working with. Output is below.

```
$ cat vn.csv | quality-check --input-format csv | jq .                                                     [±:master:≈]
/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/node_modules/object-path/index.js:61
    var intKey = parseInt(key);
                 ^

RangeError: Maximum call stack size exceeded
    at getKey (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/node_modules/object-path/index.js:61:18)
    at Function.objectPath.get (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/node_modules/object-path/index.js:238:25)
    at Function.objectPath.get (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/node_modules/object-path/index.js:235:27)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:151:37)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:174:17)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:174:17)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:174:17)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:174:17)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:174:17)
    at Flagger.flagRepeats (/Users/jflasher/.nvm/versions/node/v8.9.4/lib/node_modules/openaq-quality-checks/lib/flagger.js:174:17)
```

**Comment by abarciauskas-bgse** [comment]
@jflasher Thanks for bringing this up! It looks like the flagRepeats recursion is indeed overflowing the call stack. I should be able to put in a fix in the next couple days - likely removing the recursive call. It's hard to say exact file size since this depends on how many times `flagRepeats` is called which depends on the data itself. But for the file you provided this bug happens somewhere over 2.1MB or 6,414 rows.

**Comment by abarciauskas-bgse** [comment]
@jflasher addressed with https://github.com/openaq/openaq-quality-checks/pull/21

**Comment by abarciauskas-bgse** [comment]
`openaq-quality-checks@1.1.2` released which addresses this bug
